### ISSUE TITLE
[Bug Report] Roundtrip fails with arbitrary `Integer` values.

### ISSUE THREAD

**Issue by ruseinov** [ipld/serde_ipld_dagcbor#14]
I stumbled upon this issue while trying to generate some arbitrary `Ipld` values with quickcheck.
It turns out that arbitrary `Integer` when serialised, could potentially mess with deserialisation.

According to [this](https://ipld.io/docs/data-model/kinds/#integer-kind) spec:
```
Some codecs, such as DAG-CBOR, will assume that integers must be within the 64-bit signed range 
and reject anything larger.
```

Now, I understand that `CBOR` does not support `i128`, in which case it would be nice if it complained on serialisation. Otherwise we get a weird error on deserialisation that is really hard to debug.  

Here's some code I wrote to isolate the issue:
```rust
    #[quickcheck]
    fn minimal_test_case(int: i128) {
        let blob = serde_ipld_dagcbor::to_vec(&Ipld::Integer(int)).unwrap();
        if let Err(e) = serde_ipld_dagcbor::from_slice::<Ipld>(&blob) {
            println!("INT: {}", int);
            println!("{}", e);
        }
    }
```

Sample output:
```
INT: 99788494473546867629425321903464052941
TypeMismatch { name: "CBOR tag", byte: 2 }
```

The error triggers because of [this](https://github.com/quininer/cbor4ii/blob/master/src/core/enc.rs#L148) `Encode` implementation for `i128` or [that](https://github.com/quininer/cbor4ii/blob/master/src/core/enc.rs#L127) for `u128`, that both use tag values not supported by `serde_ipld_dagcbor` as per [this comment](https://github.com/ipld/serde_ipld_dagcbor/blob/master/src/de.rs#L177) and [that implementation](https://github.com/ipld/serde_ipld_dagcbor/blob/master/src/de.rs#L120).

A minimal test case for exactly one value:
```rust
    #[test]
    fn minimal_test_case_exact() {
        let blob =
            serde_ipld_dagcbor::to_vec(&Ipld::Integer(99788494473546867629425321903464052941))
                .unwrap();
        if let Err(e) = serde_ipld_dagcbor::from_slice::<Ipld>(&blob) {
            println!("{}", e);
        }
    }
```

The fix could be as easy as validating integers in `serialize_i128` and potentially also in `serialize_u128`, though the latter does not seem reachable as `Ipld::Integer` wraps `i128`. 
However, outside of the context of `Ipld` it might be smart to have a validation check there as well.

**Comment by rvagg** [comment]
Seems reasonable, would you be willing to attempt a PR to insert some validation @ruseinov? Checking that both i128 and u128 values fit within the +/- u64 range might be the best approach.

**Comment by ruseinov** [comment]
> Seems reasonable, would you be willing to attempt a PR to insert some validation @ruseinov? Checking that both i128 and u128 values fit within the +/- u64 range might be the best approach.

No problem, will do!

**Comment by ruseinov** [comment]
> Seems reasonable, would you be willing to attempt a PR to insert some validation @ruseinov? Checking that both i128 and u128 values fit within the +/- u64 range might be the best approach.

Just out of curiosity: the spec states that it's supposed to be limiting the `Integer` range to `i64` and some libraries rely on that. I wonder how well it plays with `Integer` represented by `+/- u64` range here. 
That said, I don't think that's blocking this issue from going forward in any way, as it's how this is implemented in `cbor4ii` anyway.

**Comment by rvagg** [comment]
A question for @vmx I suspect, but the format at least allows for +/- u64 because it encodes positive (major 0) and negative (major 1) separately. What you do above the encoding layer is a different question but you can at least put them into the bytes and read them out. It'll depend on how they are used above this layer, perhaps there are extra constraints that mean you're limited to `i64`.

**Comment by ruseinov** [comment]
> > I wonder how well it plays with `Integer` represented by `+/- u64` range here.
> 
> They should hopefully play well. We have repository with test fixtures at https://github.com/ipld/codec-fixtures, the Rust implementations currently skip the test https://github.com/ipld/codec-fixtures/blob/46e91b6d59c4159ef7b1f85226d49418a8454b8f/rust/tests/utils.rs#L8 for max-`-u64`-sized integers. Though I think it would be great supporting that.
> 
> Please note that the codec fixtures stuff is a bit tricky (e.g. I just found out that the Rust libipld DAG-JSON codec decodes such small integers as floats). So if you fix it in this repo, I'll take care that it also gets tested in that codec fixture repo.

Thanks for the explanation and the willingness to give me a hand with the fixtures. I'm looking into a fix for this repo.
