### ISSUE TITLE
[Chore] Cut a new release.

### ISSUE THREAD

**Issue by ruseinov** [ipld/serde_ipld_dagcbor#16]
Cut a new release, perhaps a minor version bump, `0.4.1`.

**Comment by ruseinov** [comment]
@vmx Just making sure this gets noticed, would be great to release these integer validation fixes!

**Comment by vmx** [comment]
@Stebalien I consider it a bug fix and would say it's a 0.4.1. Would you agree or do you think it's a 0.5? https://github.com/ipld/serde_ipld_dagcbor/pull/15 is the only change since the last release.

**Comment by Stebalien** [comment]
I agree, it's a bug fix. I'd just cut a 0.4.1 release.

Thanks!

**Comment by vmx** [comment]
I just released 0.4.1.

**Comment by ruseinov** [comment]
> I just released 0.4.1.

Thanks!
