### ISSUE TITLE
non-canonical encoding

### ISSUE THREAD

**Issue by wellcaffeinated** [ipld/serde_ipld_dagcbor#31]
Hey there. I've been using the ipld/dag-cbor library to encode my data.

I just tried using this crate to encode the same data and noticed that it encodes it in the order the struct is declared in.

Here's a test you can run:
```rs
#[test]
  fn test_canonical(){
    use serde::{Serialize, Deserialize};
    #[derive(Serialize, Deserialize, PartialEq, Debug)]
    struct First {
      a: u32,
      b: u32,
    }
    #[derive(Serialize, Deserialize, PartialEq, Debug)]
    struct Second {
      b: u32,
      a: u32,
    }

    let first = First { a: 1, b: 2 };
    let second = Second { a: 1, b: 2 };

    let first_bytes = DagCborCodec::encode_to_vec(&first).unwrap();
    let second_bytes = DagCborCodec::encode_to_vec(&second).unwrap();

    assert_eq!(first_bytes, second_bytes);

  }
```

it fails with:

```
assertion `left == right` failed
  left: [162, 97, 97, 1, 97, 98, 2]
 right: [162, 97, 98, 2, 97, 97, 1]
```

**Comment by rvagg** [comment]
@vmx do we not sort maps when it comes from a struct? It should be the first of these encodings for both cases.

**Comment by vmx** [comment]
Thanks for the bug report and the test to reproduce it. I can see where the problem is, I'm working on a fix, which hopefully also catches all other cases.

**Comment by wellcaffeinated** [comment]
Fantastic! Thanks for the quick turnaround.
